<Project Sdk="WixToolset.Sdk/5.0.2">

  <PropertyGroup>
    <OutputType>Package</OutputType>
    <OutputName>ListIt</OutputName>
    <InstallerPlatform>x64</InstallerPlatform>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="WixToolset.Util.wixext" Version="5.0.2" />
  </ItemGroup>

  <ItemGroup>
    <!-- Automatically publishes ListIt during MSI build -->
    <ProjectReference Include="..\ListIt\ListIt.csproj"
                      Publish="true"
                      Properties="Configuration=Release;RuntimeIdentifier=win-x64;SelfContained=false" />
  </ItemGroup>

</Project>
